package project.nutriscan.utils

class UtilityFunctions {

    companion object {

        fun getAdditiveFullName(code: String): String {

            // Map of additive codes to their full names
            val additivesMap = mapOf(
                /* "E100" to "Curcumin",
                 "E101" to "Riboflavin",
                 "E102" to "Tartrazine",
                 "E103" to "Alkanet",
                 "E104" to "Quinoline Yellow",
                 "E105" to "Fast Yellow",
                 "E106" to "Carmine",
                 "E106B" to "Annatto Extract",
                 "E110" to "Sunset Yellow FCF",
                 "E120" to "Cochineal Red A",
                 "E122" to "Carmoisine",
                 "E123" to "Amaranth",
                 "E124" to "Ponceau 4R",
                 "E125" to "Ponceau 6R",
                 "E126" to "Erythrosine",
                 "E127" to "Erythrosine B",
                 "E128" to "Red 2G",
                 "E129" to "Allura Red AC",
                 "E130" to "Watermelon Red",
                 "E140" to "Chlorophylls",
                 "E141" to "Copper Complexes of Chlorophylls",
                 "E150" to "Caramel",
                 "E151" to "Black PN",
                 "E160" to "Carotenoids",
                 "E161" to "Lycopene",
                 "E162" to "Beet Red",
                 "E163" to "Anthocyanins",
                 "E170" to "Calcium Carbonate",
                 "E171" to "Titanium Dioxide",
                 "E172" to "Iron Oxides",
                 "E173" to "Aluminum",
                 "E200" to "Sorbic Acid",
                 "E202" to "Potassium Sorbate",
                 "E210" to "Benzoic Acid",
                 "E211" to "Sodium Benzoate",
                 "E220" to "Sulfur Dioxide",
                 "E221" to "Sodium Sulfite",
                 "E222" to "Sodium Bisulfite",
                 "E223" to "Sodium Metabisulfite",
                 "E224" to "Potassium Metabisulfite",
                 "E250" to "Sodium Nitrite",
                 "E251" to "Sodium Nitrate",
                 "E252" to "Potassium Nitrate",
                 "E300" to "Ascorbic Acid",
                 "E301" to "Sodium Ascorbate",
                 "E302" to "Calcium Ascorbate",
                 "E330" to "Citric Acid",
                 "E331" to "Sodium Citrate",
                 "E332" to "Potassium Citrate",
                 "E333" to "Calcium Citrate",
                 "E334" to "Tartaric Acid",
                 "E335" to "Sodium Tartrate",
                 "E336" to "Potassium Tartrate",
                 "E337" to "Sodium Potassium Tartrate",
                 "E400" to "Agar",
                 "E401" to "Sodium Alginate",
                 "E402" to "Potassium Alginate",
                 "E500" to "Sodium carbonate.",
                 "E500II" to "Sodium Bicarbonate."
                 */


                "E100" to "Curcumin",
                "E101" to "Riboflavin (Vitamin B2)",
                "E102" to "Tartrazine",
                "E104" to "Quinoline Yellow",
                "E110" to "Sunset Yellow FCF",
                "E120" to "Cochineal, Carminic acid",
                "E130" to "Chlorophylls and Chlorophyllins",
                "E140" to "Chlorophyll",
                "E150A" to "Caramel (Plain)",
                "E150B" to "Caustic soda caramel",
                "E150C" to "Ammonia caramel",
                "E150D" to "Sulfite ammonia caramel",
                "E160A" to "Carotenoids (Beta-carotene)",
                "E160B" to "Annatto, bixin, and norbixin",
                "E160C" to "Paprika extract",
                "E160D" to "Lycopene",
                "E160E" to "Ethyl ester of beta-apo-8′-carotenal",
                "E161" to "Flavoxanthin",
                "E171" to "Titanium Dioxide",
                "E172" to "Iron Oxides",
                "E173" to "Aluminum",


                "E200" to "Sorbic acid",
                "E202" to "Potassium sorbate",
                "E210" to "Benzoic acid",
                "E211" to "Sodium benzoate",
                "E212" to "Potassium benzoate",
                "E213" to "Calcium benzoate",
                "E214" to "Ethyl p-hydroxybenzoate",
                "E215" to "Sodium ethyl p-hydroxybenzoate",
                "E218" to "Methyl p-hydroxybenzoate",
                "E219" to "Sodium methyl p-hydroxybenzoate",
                "E220" to "Sulfur dioxide",
                "E221" to "Sodium sulphite",
                "E222" to "Sodium hydrogen sulphite",
                "E223" to "Sodium metabisulphite",
                "E224" to "Potassium metabisulphite",
                "E226" to "Calcium sulphite",
                "E227" to "Calcium hydrogen sulphite",
                "E228" to "Potassium hydrogen sulphite",
                "E234" to "Nisin",
                "E235" to "Natamycin",
                "E239" to "Hexamethylene tetramine",
                "E242" to "Dimethyl dicarbonate",
                "E243" to "Ethyl lauroyl arginate",
                "E249" to "Potassium nitrite",
                "E250" to "Sodium nitrite",
                "E251" to "Sodium nitrate",
                "E252" to "Potassium nitrate",
                "E280" to "Propionic acid",
                "E281" to "Sodium propionate",
                "E282" to "Calcium propionate",
                "E283" to "Potassium propionate",
                "E284" to "Boric acid",
                "E285" to "Sodium tetraborate; borax",
                "E1105" to "Lysozyme",


                "E300" to "Ascorbic acid (Vitamin C)",
                "E301" to "Sodium ascorbate",
                "E302" to "Calcium ascorbate",
                "E304" to "Fatty acid esters of ascorbic acid",
                "E306" to "Tocopherol (Vitamin E)",
                "E307" to "Alpha-tocopherol",
                "E308" to "Gamma-tocopherol",
                "E309" to "Delta-tocopherol",
                "E310" to "Propyl gallate",
                "E315" to "Erythorbic acid",
                "E316" to "Sodium erythorbate",
                "E319" to "Tertiary-butyl hydroquinone (TBHQ)",
                "E320" to "Butylated hydroxyanisole (BHA)",
                "E322" to "Lecithins",
                "E321" to "Butylated hydroxytoluene (BHT)",
                "E330" to "Citric Acid",
                "E331" to "Sodium Citrate",
                "E332" to "Potassium Citrate",
                "E333" to "Calcium Citrate",
                "E334" to "Tartaric Acid",
                "E335" to "Sodium Tartrate",
                "E336" to "Potassium Tartrate",
                "E337" to "Sodium Potassium Tartrate",
                "E392" to "Extracts of rosemary",
                "E586" to "4-Hexylresorcinol",

                "E400" to "Alginic acid",
                "E401" to "Sodium alginate",
                "E402" to "Potassium alginate",
                "E403" to "Ammonium alginate",
                "E404" to "Calcium alginate",
                "E405" to "Propane-1,2-diol alginate; propylene glycol alginate (PGA)",
                "E406" to "Agar",
                "E407" to "Carrageenan (Irish moss)",
                "E407A" to "Processed eucheuma seaweed",
                "E410" to "Locust bean gum; carob gum",
                "E412" to "Guar gum (cluster bean gum)",
                "E413" to "Tragacanth",
                "E414" to "Acacia gum; gum arabic",
                "E415" to "Xanthan gum",
                "E416" to "Karaya gum",
                "E417" to "Tara gum",
                "E418" to "Gellan gum",
                "E425" to "Konjac",
                "E426" to "Soybean hemicellulose",
                "E427" to "Cassia gum",
                "E432" to "Polyoxyethylene sorbitan monolaurate; Polysorbate 20",
                "E433" to "Polyoxyethylene sorbitan mono-oleate; Polysorbate 80",
                "E434" to "Polyoxyethylene sorbitan monopalmitate; Polysorbate 40",
                "E435" to "Polyoxyethylene sorbitan monostearate; Polysorbate 60",
                "E436" to "Polyoxyethylene sorbitan tristearate; Polysorbate 65",
                "E440A" to "Pectin",
                "E440B" to "Amidated pectin",
                "E442" to "Ammonium phosphatide",
                "E444" to "Sucrose acetate isobutyrate",
                "E445" to "Glycerol esters of wood rosins",
                "E451" to "Triphosphates",
                "E460" to "Cellulose",
                "E461" to "Methyl cellulose",
                "E462" to "Ethyl cellulose",
                "E463" to "Hydroxypropyl cellulose",
                "E464" to "Hydroxypropyl methyl cellulose",
                "E465" to "Ethyl methyl cellulose",
                "E466" to "Carboxymethyl cellulose",
                "E468" to "Crosslinked sodium carboxymethyl cellulose",
                "E469" to "Enzymatically hydrolysed carboxymethyl cellulose",
                "E470A" to "Sodium, potassium, and calcium salts of fatty acids",
                "E470B" to "Magnesium salts of fatty acids",
                "E471" to "Mono- and diglycerides of fatty acids",
                "E472A" to "Acetic acid esters of mono- and diglycerides of fatty acids",
                "E472B" to "Lactic acid esters of mono- and diglycerides of fatty acids",
                "E472C" to "Citric acid esters of mono- and diglycerides of fatty acids",
                "E472D" to "Tartaric acid esters of mono- and diglycerides of fatty acids",
                "E472E" to "Mono- and diacetyltartaric acid esters of mono- and diglycerides of fatty acids",
                "E472F" to "Mixed acetic and tartaric acid esters of mono- and diglycerides of fatty acids",
                "E473" to "Sucrose esters of fatty acids",
                "E474" to "Sucroglycerides",
                "E475" to "Polyglycerol esters of fatty acids",
                "E476" to "Polyglycerol polyricinoleate",
                "E477" to "Propane-1,2-diol esters of fatty acids",
                "E479B" to "Thermally oxidised soya bean oil interacted with mono- and diglycerides of fatty acids",
                "E481" to "Sodium stearoyl-2-lactylate",
                "E482" to "Calcium stearoyl-2-lactylate",
                "E483" to "Stearyl tartrate",
                "E491" to "Sorbitan monostearate",
                "E492" to "Sorbitan tristearate",
                "E493" to "Sorbitan monolaurate",
                "E494" to "Sorbitan monooleate",
                "E495" to "Sorbitan monopalmitate",
                "E1103" to "Invertase",

                "E500" to "Sodium carbonates",
                "E500II" to "Sodium Bicarbonate.",
                "E501" to "Potassium carbonates",
                "E502" to "Ammonium carbonates",
                "E503" to "Magnesium carbonates",
                "E504" to "Calcium carbonates",
                "E507" to "Hydrochloric acid- Acidity Regulators",
                "E508" to "Potassium chloride",
                "E510" to "Ammonium chloride",
                "E511" to "Magnesium chloride",
                "E520" to "Aluminium sulfate",
                "E522" to "Aluminium potassium sulfate",
                "E524" to "Sodium hydroxide",
                "E525" to "Potassium hydroxide",
                "E526" to "Calcium hydroxide",
                "E530" to "Magnesium hydroxide",
                "E535" to "Sodium ferrocyanide",
                "E536" to "Potassium ferrocyanide",
                "E538" to "Calcium ferrocyanide",
                "E551" to "Silicon dioxide",
                "E552" to "Calcium silicate",
                "E553A" to "Magnesium silicate",
                "E553B" to "Talc",
                "E554" to "Sodium aluminosilicate",
                "E555" to "Potassium aluminosilicate",
                "E556" to "Calcium aluminosilicate",
                "E557" to "Magnesium aluminosilicate",
                "E558" to "Kaolin",
                "E560" to "Calcium carbonate",
                "E570" to "Stearic acid",
                "E571" to "Sodium stearate",
                "E572" to "Magnesium stearate",
                "E580" to "Tartaric acid",
                "E585" to "Ferrous lactate",

                "E620" to "Glutamic acid",
                "E621" to "Monosodium glutamate (MSG)",
                "E622" to "Monopotassium glutamate",
                "E623" to "Calcium glutamate",
                "E624" to "Magnesium glutamate",
                "E625" to "Monoammonium glutamate",
                "E630" to "Inosinic acid",
                "E631" to "Disodium inosinate",
                "E632" to "Calcium inosinate",
                "E635" to "Sodium-5-ribonucleotide",
                "E640" to "Glycine and its salts",
                "E650" to "Lactic acid",
                "E660" to "Lactic acid salts",
                "E670" to "Tannins",
                "E671" to "Tannic acid",
                "E672" to "Calcium tannate",
                "E673" to "Potassium tannate",
                "E680" to "Acetic acid",
                "E690" to "Propionic acid",
                "E700" to "Alcohols",
                "E900" to "Dimethylpolysiloxane",
                "E901" to "Beeswax",
                "E902" to "Shellac",
                "E903" to "Carnauba wax",
                "E904" to "Natural waxes",
                "E910" to "Lecithins",
                "E920" to "L-Cysteine",
                "E950" to "Acesulfame K",
                "E951" to "Aspartame",
                "E952" to "Cyclamate",
                "E953" to "Isomalt",
                "E954" to "Saccharin",
                "E955" to "Stevia",
                "E957" to "Thaumatin",
                "E960" to "Steviol glycosides",
                "E965" to "Maltitol",
                "E967" to "Xylitol",
                "E999" to "Saccharin sodium"

            )

            // Return the full name or "Unknown Additive" if not found

            return additivesMap[code] ?: "Unknown Additive"

        }
    }
}